services:
  audiobookshelf:
    container_name: audiobookshelf
    image: ghcr.io/advplyr/audiobookshelf:latest
    ports:
      - 13378:80
    networks:
      - proxy
    volumes:
      - /mnt/staging/audiobookshelf/audiobooks:/audiobooks
      - /mnt/staging/audiobookshelf/podcasts:/podcasts
      - ${HOME}/pods/audiobookshelf:/config
      - /mnt/staging/tmp/audiobookshelf:/metadata
    environment:
      - TZ=America/Panama
