services:
  epub_to_audiobook:
    container_name: epub_to_audiobook
    image: ghcr.io/p0n1/epub_to_audiobook:latest
    environment:
      MS_TTS_KEY: ''
      MS_TTS_REGION:  ''
      # for custom OpenAI-compatible endpoints
      # OPENAI_BASE_URL: <your_openai_base_url>
      OPENAI_API_KEY: ''
    ports:
      - "7860:7860"
    networks:
      - proxy
    volumes:
      - ${HOME}/pods/epub_audiobook:/app
    command: 'python3 /app_src/main_ui.py --host 0.0.0.0 --port 7860'
