services:
  glance:
    image: glanceapp/glance
    container_name: glance
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Panama
    volumes:
      - ${HOME}/pods/glance/config:/app/config
    ports:
      - 8888:8080
    networks:
      - proxy
 #   restart: unless-stopped
  
