services:
  iptvbackend:
    container_name: iptvbackend
    image: 4gray/iptvnator-backend:latest
    ports:
      - "7333:3000"
    networks:
      - proxy
    environment:
      - CLIENT_URL=http://hermes.tandil.lan:4333 
      # this one should match with the address and port in frontend CLIENT_URL env
      
  iptvfrontend: 
    container_name: iptvfrontend
    image: 4gray/iptvnator:latest
    ports:
      - "4333:80"
    networks:
      - proxy
    environment:
      - BACKEND_URL=http://hermes.tandil.lan:7333 
      # this one should match with the address of the backend service
      
