services:
  mediagui:
    container_name: mediagui
    image: ghcr.io/jbrodriguez/mediagui
    env_file: .env-mediagui
    environment:
      - TZ=America/Panama
    volumes:
      - ${HOME}/pods/mediagui/data:/data
    ports:
      - "7623:7623"
    networks:
      - proxy

