services:
  navidrome:
    container_name: navidrome
    image: deluan/navidrome:latest
    user: 1000:1000 # should be owner of volumes
    ports:
      - "4533:4533"
#    restart: unless-stopped
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.navidrome.rule=Host(`navidrome.lan.jbrio.net`)
      - traefik.http.routers.navidrome.entrypoints=websecure
      - traefik.http.routers.navidrome.tls=true
      - traefik.http.routers.navidrome.tls.certresolver=cloudflare
      - traefik.http.routers.navidrome.middlewares=lan-only
      - traefik.http.services.navidrome.loadbalancer.server.port=4533
    environment:
      # Optional: put your config options customization here. Examples:
      ND_SCANSCHEDULE: 1h
      ND_LOGLEVEL: info  
      ND_SESSIONTIMEOUT: 24h
      ND_BASEURL: ""
      ND_PLAYLISTSPATH: "."
    volumes:
      - ${HOME}/pods/navidrome:/data
      - "/mnt/storage/bbmusic/media:/music:ro"
