services:
  nzbget:
    container_name: nzbget
    image: ghcr.io/hotio/nzbget
    ports:
      - "7010:6789"
    networks:
      - proxy
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=America/Panama
    volumes:
      - ${HOME}/pods/nzbget/config:/config
      - /mnt/ark/content/usenet:/data/usenet
      - /mnt/tank/cache/nzbget:/cache
      - /mnt/staging/usenet/adult:/adult
      - /mnt/staging/usenet/films:/films
