services:
  qbittorrent:
    container_name: qbittorrent
    image: ghcr.io/hotio/qbittorrent:release-5.1.0
    ports:
      - "7020:8080"
    networks:
      - proxy
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=America/Panama
      - WEBUI_PORTS=8080/tcp,8080/udp
    volumes:
      - ${HOME}/pods/qbittorrent/config:/config
      - /mnt/ark/content/torrents:/data/torrents
