services:
  qui:
    container_name: qui
    image: ghcr.io/autobrr/qui:latest
    ports:
      - "7080:7476"
    networks:
      - proxy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Panama
    volumes:
      - ${HOME}/pods/qbittorrent/config:/config
      - /mnt/ark/content/torrents:/data/torrents
