services:
  radarr:
    container_name: radarr
    image: ghcr.io/hotio/radarr
    ports:
      - "7030:7878"
    networks:
      - proxy
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=America/Panama
    volumes:
      - ${HOME}/pods/radarr/config:/config
      - /mnt/ark/content:/data
