services:
  soulseek:
    container_name: soulseek
    image: realies/soulseek
    volumes:
      - /mnt/staging/soulseek/appdata:/data/.SoulseekQt
      - /mnt/staging/soulseek/downloads:/data/Soulseek Downloads
      - /mnt/staging/soulseek/logs:/data/Soulseek Chat Logs
      - /mnt/staging/soulseek/shared:/data/Soulseek Shared Folder
    environment:
      - PGID=1000
      - PUID=1000
    networks:
      - proxy
    ports:
      - 6080:6080
      - 61122:61122 # example listening port, check Options -> Login
      - 61123:61123 # example obfuscated port, check Options -> Login

