services:
  tabula:
    container_name: tabula
    init: true
    build:
      context: ${HOME}/pods/tabula/config
      dockerfile: ${HOME}/pods/tabula/config/Dockerfile
    ports:
      - 8080:8080
    networks:
      - proxy
    environment:
      HOST: 0.0.0.0
      PORT: 8080
  
