services:
  yt-dlp:
    container_name: yt-dlp
    image: marcobaobao/yt-dlp-webui
    ports:
      - 3033:3033
    networks:
      - proxy
    volumes:
      - /mnt/staging/tmp:/downloads # replace <your dir> with a directory on your host system
      - ${HOME}/pods/yt_dlp:/config
    healthcheck:
      test: curl -f http://localhost:3033 || exit 1
