services:
  zars:
    image: ghcr.io/jbrodriguez/zars
    container_name: zars
    env_file: .env-zars
    environment:
      - TZ=America/Panama
    volumes:
      - ${HOME}/pods/zars/config:/config
      - ${HOME}/pods/zars/data:/data
      - /mnt/staging/bridge/source:/downloads
    ports:
      - "7028:7028"
    networks:
      - proxy
