services:
  zars:
    image: ghcr.io/jbrodriguez/zars
    container_name: zars
    env_file: .env-zars
    environment:
      - TZ=America/Panama
    volumes:
      - ${HOME}/pods/zars/config:/config
      - ${HOME}/pods/zars/data:/data
      - /mnt/staging/bridge/source:/downloads
    ports:
      - "7028:7028"
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.zars.rule=Host(`zars.lan.jbrio.net`)
      - traefik.http.routers.zars.entrypoints=websecure
      - traefik.http.routers.zars.tls=true
      - traefik.http.routers.zars.tls.certresolver=cloudflare
      - traefik.http.routers.zars.middlewares=lan-only
      - traefik.http.services.zars.loadbalancer.server.port=7028
